
run: 
	../../run_javatrace.sh -jar ThreadPool.jar

runshow:
	../../run_javatrace.sh -jar -show ThreadPool.jar

show:
	../../show_trace.sh -conf ThreadPool.pcf -row ThreadPool.row ThreadPool.prv

clean:
	rm -fr *.csv *.class set-0 TRACE.* *.pcf *.row *.prv extraej.*
