
run: 
	./run_javatrace.sh -jar Futures.jar

runshow:
	./run_javatrace.sh -jar -show Futures.jar

show:
	./show_trace.sh -conf Futures.pcf -row Futures.row Futures.prv

clean:
	rm -fr *.csv *.class set-0 TRACE.* *.pcf *.row *.prv extraej.*
