
run: 
	../../run_javatrace.sh -jar Futures.jar Main

runshow:
	../../run_javatrace.sh -jar Futures.jar -show Main

show:
	../../show_trace.sh -conf Futures.pcf -row Futures.row Futures.prv

clean:
	rm -fr *.csv *.class set-0 TRACE.* *.pcf *.row *.prv extraej.*
