
run: 
	../../run_javatrace.sh -jar ForkJoin.jar

runshow:
	../../run_javatrace.sh -jar -show ForkJoin.jar

show:
	../../show_trace.sh -conf ForkJoin.pcf -row ForkJoin.row ForkJoin.prv

clean:
	rm -fr *.csv *.class set-0 TRACE.* *.pcf *.row *.prv extraej.*
