run:
	../../run_javatrace.sh -r -mvn  org.apache.hadoop.examples.WordCount

runshow:
	../../run_javatrace.sh -r -mvn -show org.apache.hadoop.examples.WordCount

show:
	../../show_trace.sh -conf hadoop.pcf -row hadoop.row hadoop.prv

clean:
	rm -rf *.csv *.class set-0 TRACE.* *.pcf *.row *.prv extraej* target jars output*
