
run: 
	./run_javatrace.sh -jar PiExample.jar

runshow:
	./run_javatrace.sh -jar -show PiExample.jar

show:
	./show_trace.jar -conf PiExample.pcf -row PiExample.row PiExample.prv

clean:
	rm -fr *.class set-0 TRACE.* *.pcf *.row *.prv extraej.*
